title: UBMLtonGroup
description: Adventures in Embedded RT SML
author: UBMLtonGroup
logo: /static/img/avatar.png
github: https://github.com/ubmltongroup
about: Research Group at University at Buffalo

baseurl: ""
url: "http://aboutashu.com/hcz-jekyll-blog"

#disqus_shortname: ubmltongroup
google_analytics: UA-83208484-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
